# This file is part of "echion" which is released under MIT.
#
# Copyright (c) 2023 Gabriele N. Tornetta <phoenix1987@gmail.com>.

def start() -> None: ...
def start_async() -> None: ...
def stop() -> None: ...
def track_thread(thread_id: int, name: str) -> None: ...
def untrack_thread(thread_id: int) -> None: ...
def init() -> None: ...

# Configuration interface
def set_interval(interval: int) -> None: ...
def set_cpu(cpu: bool) -> None: ...
def set_native(native: bool) -> None: ...
def set_where(where: bool) -> None: ...
