name: Benchmarks

on:
  pull_request:
    paths:
      - .github/workflows/benchmarks.yml
      - scripts/benchmark.py
      - scripts/requirements-bm.txt
      - src/**

jobs:
  benchmarks:
    permissions:
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Install Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - uses: actions/checkout@v3
        with:
          path: echion

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: echion-base

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdb liblzma-dev
          cd echion
          sudo -E bash scripts/build_libunwind.sh
          cd -
          pip install pygments

      - name: Compile Echion from the base branch
        run: |
          python3.13 -m venv echion/.venv-base
          source echion/.venv-base/bin/activate
          pip install -e ./echion-base
          deactivate

      - name: Compile Echion from the PR
        run: |
          python3.13 -m venv echion/.venv
          source echion/.venv/bin/activate
          pip install -e ./echion
          deactivate

      - name: Install runtime dependencies
        run: |
          python3.13 -m venv .venv-bm
          source .venv-bm/bin/activate
          pip install -r echion/scripts/requirements-bm.txt
          deactivate

      - name: Run benchmarks
        shell: bash
        env:
          PYTHONPATH: "."
        run: |
          set -eo pipefail
          ulimit -c unlimited
          echo "core.%p" | sudo tee /proc/sys/kernel/core_pattern
          source .venv-bm/bin/activate
          cd echion
          python scripts/benchmark.py --format markdown | tee ${{ github.workspace}}/comment.txt
          cd -

      - name: Post results on PR
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
        with:
          header: benchmarks
          path: ${{ github.workspace}}/comment.txt
